### ISSUE TITLE
Flutter null safety

### ISSUE THREAD

**Issue by deepbhavsar** [QuickBlox/quickblox-flutter-sdk#19] opened 2021-04-29 09:41 UTC
Require to migrate. Almost dependancy migrated, we have to set plank for this dependancy.

**Comment by kirillTolmachev** [comment] 2021-05-25 15:12
@deepbhavsar 
Yes, we are working on it.

**Comment by axu6705** [comment] 2021-06-01 16:04
> @deepbhavsar
> Yes, we are working on it.

When can the migration be completed.

**Comment by axu6705** [comment] 2021-06-04 16:07
@kirillTolmachev 
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.928], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.2)
[√] Connected device (3 available)
```

```
Launching lib\main.dart on sdk gphone x86 in debug mode...
package:chat/main.dart:1
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:60757/1fMlPQ7ImzA=/ws
E/flutter (21764): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter (21764): #0      MethodChannel.binaryMessenger
package:flutter/…/services/platform_channel.dart:142
E/flutter (21764): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:148
E/flutter (21764): #2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:331
E/flutter (21764): #3      Settings.init
package:quickblox_sdk/settings/module.dart:53
E/flutter (21764): #4      init
package:chat/main.dart:16
E/flutter (21764): #5      main
package:chat/main.dart:28
E/flutter (21764): #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter (21764): #7      _rootRun (dart:async/zone.dart:1354:13)
E/flutter (21764): #8      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (21764): #9      _runZoned (dart:async/zone.dart:1789:10)
E/flutter (21764): #10     runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter (21764): #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter (21764): #12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter (21764): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (21764):
```

**Comment by kirillTolmachev** [comment] 2021-06-11 11:34
@axu6705 , @deepbhavsar 
We have released a new version 0.5.0-beta with null-safety.

**Comment by axu6705** [comment] 2021-06-11 15:11
> @axu6705 , @deepbhavsar
> We have released a new version 0.5.0-beta with null-safety.

Great, let me try

**Comment by ghost** [comment] 2021-10-05 13:38
Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant.

**Comment by ghost** [comment] 2021-12-07 12:55
@axu6705 @deepbhavsar The issue is being closed as outdated.

If the issue is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 12:55 UTC
