### ISSUE TITLE
Crash on release apk 

### ISSUE THREAD

**Issue by roldanunne** [QuickBlox/quickblox-flutter-sdk#46] opened 2021-12-16 06:35 UTC
The app working properly in debug mode.
But if I run it using 'flutter run --release' it will crash with ff error below
I'm using the latest release quickblox_sdk: ^0.6.4-beta
Is it crashing because I'm using free account?

E/AndroidRuntime(22194): FATAL EXCEPTION: main
E/AndroidRuntime(22194): Process: com.example.kshfyah_mobile_app, PID: 22194
E/AndroidRuntime(22194): java.lang.ExceptionInInitializerError
E/AndroidRuntime(22194): at f.a.a.m.h(Unknown Source:0)
E/AndroidRuntime(22194): at f.a.a.d.(Unknown Source:0)
E/AndroidRuntime(22194): at c.d.b.g.(Unknown Source:0)
E/AndroidRuntime(22194): at c.d.b.g.b0(Unknown Source:0)
E/AndroidRuntime(22194): at c.d.h.m.b.h(Unknown Source:209)
E/AndroidRuntime(22194): at c.d.h.m.b.g(Unknown Source:101)
E/AndroidRuntime(22194): at c.d.h.m.a.g(Unknown Source:2)
E/AndroidRuntime(22194): at d.a.c.a.j$a.a(Unknown Source:17)
E/AndroidRuntime(22194): at io.flutter.embedding.engine.f.c.h(Unknown Source:18)
E/AndroidRuntime(22194): at io.flutter.embedding.engine.f.c.i(Unknown Source:20)
E/AndroidRuntime(22194): at io.flutter.embedding.engine.f.c.j(Unknown Source:0)
E/AndroidRuntime(22194): at io.flutter.embedding.engine.f.a.run(Unknown Source:12)
E/AndroidRuntime(22194): at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(22194): at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(22194): at android.os.Looper.loop(Looper.java:263)
E/AndroidRuntime(22194): at android.app.ActivityThread.main(ActivityThread.java:8276)
E/AndroidRuntime(22194): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22194): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
E/AndroidRuntime(22194): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
E/AndroidRuntime(22194): Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: org.jivesoftware.smack.initializer.VmArgInitializer
E/AndroidRuntime(22194): at f.a.a.o.(Unknown Source:202)
E/AndroidRuntime(22194): ... 19 more
E/AndroidRuntime(22194): Caused by: java.lang.ClassNotFoundException: org.jivesoftware.smack.initializer.VmArgInitializer
E/AndroidRuntime(22194): at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(22194): at java.lang.Class.forName(Class.java:454)
E/AndroidRuntime(22194): at f.a.a.o.a(Unknown Source:1)
E/AndroidRuntime(22194): at f.a.a.o.b(Unknown Source:34)
E/AndroidRuntime(22194): at f.a.a.o.d(Unknown Source:39)
E/AndroidRuntime(22194): at f.a.a.o.c(Unknown Source:6)
E/AndroidRuntime(22194): at f.a.a.o.(Unknown Source:144)
E/AndroidRuntime(22194): ... 19 more
E/AndroidRuntime(22194): Caused by: java.lang.ClassNotFoundException: org.jivesoftware.smack.initializer.VmArgInitializer
E/AndroidRuntime(22194): ... 26 more

**Comment by ghost** [comment] 2021-12-22 10:11
Hello @roldanunne The issue is being closed as a duplicate.

Let's continue conversation in https://github.com/QuickBlox/quickblox-flutter-samples/issues/7

**Closed as completed by ghost** 2021-12-22 10:11 UTC
