### ISSUE TITLE
Flutter error on running on  release apk  , help me ..

### ISSUE THREAD

**Issue by ruangngedotcom** [QuickBlox/quickblox-flutter-sdk#27] opened 2021-07-18 11:36 UTC

**Comment by ghost** [comment] 2021-10-05 14:08
Hello, 

This is Nikolay from QuickBlox support.

In order to investigate the issue, please provide me with the following points:
1. Version of QuickBlox Flutter SDK.
2. Version of the platform (e.g. Android 11).
3. Devices in use (e.g. Redmi 8)
4. Flutter version.
5. Dart version.
6. Steps to reproduce the issue.
7. Please provide us with full REST + XMPP logs as an attachment in .txt format. 
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/section/14-gathering-logs-guides)

**Comment by ghost** [comment] 2021-12-07 12:57
@rifkydioninkaokr The issue is being closed as outdated.

If the issue is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 12:57 UTC
