### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code on xcode 11.2

### ISSUE THREAD

**Issue by deepbhavsar** [QuickBlox/quickblox-flutter-sdk#23] opened 2021-05-17 10:42 UTC
I am using the latest flutter with Xcode 11.2, set target version 13 for pod and deployment.

I am getting below error from latest version as well as some old versions:

PhaseScriptExecution [CP]\ Copy\ XCFrameworks /Developer/Xcode/DerivedData/Runner-hagmvhqarzsninglzxtzrmsdiddg/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/QuickBlox.build/Script-2E20A8897D77C58709B96F967C92CB21.sh (in target 'QuickBlox' from project 'Pods')
    cd /flutterdemo/demo_quickblox_2/ios/Pods
    /bin/sh -c /Developer/Xcode/DerivedData/Runner-hagmvhqarzsninglzxtzrmsdiddg/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/QuickBlox.build/Script-2E20A8897D77C58709B96F967C92CB21.sh

/flutterdemo/demo_quickblox_2/ios/Pods/Target Support Files/QuickBlox/QuickBlox-xcframeworks.sh: line 35: ARCHS: unbound variable
Selected xcframework slice /flutterdemo/demo_quickblox_2/ios/Pods/QuickBlox/Framework/Quickblox.xcframework
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" "/flutterdemo/demo_quickblox_2/ios/Pods/QuickBlox/Framework/Quickblox.xcframework/flutterdemo/demo_quickblox_2/ios/Pods/QuickBlox/Framework/Quickblox.xcframework/" "/Developer/Xcode/DerivedData/Runner-hagmvhqarzsninglzxtzrmsdiddg/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/Quickblox"
building file list ... rsync: link_stat "/flutterdemo/demo_quickblox_2/ios/Pods/QuickBlox/Framework/Quickblox.xcframework/flutterdemo/demo_quickblox_2/ios/Pods/QuickBlox/Framework/Quickblox.xcframework/." failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/main.c(996) [sender=2.6.9]
Command PhaseScriptExecution failed with a nonzero exit code
____

I am stuck with it. share a solution for it.

**Comment by deepbhavsar** [comment] 2021-05-17 10:44
I have searched for **ARCHS: unbound variable** and applied some solutions but they have not worked.

**Comment by kirillTolmachev** [comment] 2021-05-18 09:03
@deepbhavsar 
Please try to clean a flutter cache (ios as well) and repair (remove/add) the POD file.

**Comment by deepbhavsar** [comment] 2021-05-18 11:51
Hello @kirillTolmachev , I have tried it but getting same error. I have manually delete pods, install pods, flutter clean, flutter cache repair etc are applied too.

Launching lib/main.dart on iPhone 11 in debug mode...
Running Xcode build...
Xcode build done.                                            6.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /flutterdemo/demo_quickblox_2/ios/Pods/Target Support Files/QuickBlox/QuickBlox-xcframeworks.sh: line 35: ARCHS: unbound variable
    Selected xcframework slice /flutterdemo/demo_quickblox_2/ios/Pods/QuickBlox/Framework/Quickblox.xcframework
    rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" "/flutterdemo/demo_quickblox_2/ios/Pods/QuickBlox/Framework/Quickblox.xcframework//flutterdemo/demo_quickblox_2/ios/Pods/QuickBlox/Framework/Quickblox.xcframework/" "/flutterdemo/demo_quickblox_2/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/Quickblox"
    building file list ... rsync: link_stat "/flutterdemo/demo_quickblox_2/ios/Pods/QuickBlox/Framework/Quickblox.xcframework//flutterdemo/demo_quickblox_2/ios/Pods/QuickBlox/Framework/Quickblox.xcframework/." failed: No such file or directory (2)
    done

    sent 29 bytes  received 20 bytes  98.00 bytes/sec
    total size is 0  speedup is 0.00
    rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/main.c(996) [sender=2.6.9]
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'QuickBlox' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Pods-Runner' from project 'Pods')
    warning: None of the architectures in ARCHS (x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Pods-Runner' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Runner' from project 'Runner')
    warning: None of the architectures in ARCHS (x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Runner' from project 'Runner')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Quickblox-WebRTC' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 11.

**Comment by kirillTolmachev** [comment] 2021-05-18 13:07
@deepbhavsar
Please try to build in the same way but our samples and notify the error appears as well or not:
**https://github.com/QuickBlox/quickblox-flutter-samples**

**Comment by deepbhavsar** [comment] 2021-05-19 11:39
Hello @kirillTolmachev 
it is giving me the same error for this demo. This demo is using quickblox_sdk: ^0.4.0-alpha. Also, it showing me a warning for migrating the Android project.

I have also tried with different xcode and getting the same error.

Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Running pod install...
Running Xcode build...
Xcode build done.                                            6.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Deep/flutterdemo/1/quickblox-flutter-samples-master/ios/Pods/Target Support Files/QuickBlox/QuickBlox-xcframeworks.sh: line 35: ARCHS: unbound variable
    Selected xcframework slice /Deep/flutterdemo/1/quickblox-flutter-samples-master/ios/Pods/QuickBlox/Framework/Quickblox.xcframework
    rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" "/Deep/flutterdemo/1/quickblox-flutter-samples-master/ios/Pods/QuickBlox/Framework/Quickblox.xcframework//Deep/flutterdemo/1/quickblox-flutter-samples-master/ios/Pods/QuickBlox/Framework/Quickblox.xcframework/" "/Deep/flutterdemo/1/quickblox-flutter-samples-master/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/Quickblox"
    building file list ... rsync: link_stat "/Deep/flutterdemo/1/quickblox-flutter-samples-master/ios/Pods/QuickBlox/Framework/Quickblox.xcframework//Deep/flutterdemo/1/quickblox-flutter-samples-master/ios/Pods/QuickBlox/Framework/Quickblox.xcframework/." failed: No such file or directory (2)
    done

    sent 29 bytes  received 20 bytes  98.00 bytes/sec
    total size is 0  speedup is 0.00
    rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/main.c(996) [sender=2.6.9]
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Pods-Runner' from project 'Pods')
    warning: None of the architectures in ARCHS (x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Pods-Runner' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'QuickBlox' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Runner' from project 'Runner')
    warning: None of the architectures in ARCHS (x86_64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (i386, x86_64) which is not in EXCLUDED_ARCHS (x86_64). (in target 'Runner' from project 'Runner')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'Quickblox-WebRTC' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 11.

**Comment by kirillTolmachev** [comment] 2021-05-19 15:32
@deepbhavsar
Today we have released a new version of Flutter Quickblox SDK with a hotfix for IOS side. 
Please update to version 0.4.3-beta and try again.

**Comment by deepbhavsar** [comment] 2021-05-21 09:49
@kirillTolmachev ,

It is giving the same error with xcode 11.2 but I deleted the ios folder from the flutter project, create new project of ios and use xcode 12.4 then it works only.

**Comment by kirillTolmachev** [comment] 2021-05-25 15:10
@deepbhavsar 
Can I close the issue?

**Comment by ghost** [comment] 2021-10-05 13:39
@deepbhavsar Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant.

**Comment by ghost** [comment] 2021-12-07 12:56
@deepbhavsar The issue is being closed as outdated.

If the issue is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 12:56 UTC
