### ISSUE TITLE
Crash on sending message in android

### ISSUE THREAD

**Issue by ArunAR-IL** [QuickBlox/quickblox-flutter-sdk#28] opened 2021-07-20 03:35 UTC
I'm getting irregular crash while sending message into a public dialog.

 await QB.chat.sendMessage(dialogId, body: messageBody, attachments: attachments, saveToHistory: true,properties: properties);

_E/AndroidRuntime(10204): java.lang.IllegalStateException: You have not joined chat room!
E/AndroidRuntime(10204): 	at com.quickblox.chat.QBGroupChat.sendMessage(Unknown Source:16)
E/AndroidRuntime(10204): 	at com.quickblox.chat.QBAbstractChat$a.performInAsync(Unknown Source:4)
E/AndroidRuntime(10204): 	at com.quickblox.chat.utils.ThreadTaskEx.run(Unknown Source:0)
E/AndroidRuntime(10204): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(10204): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(10204): 	at java.lang.Thread.run(Thread.java:919)_

I'm performing the necessary steps like  login,connecting to chat server and joining dialog as per the doc. This issue not happening every time. Otherwise it is working perfect!

**Comment by ghost** [comment] 2021-08-12 09:28
Hello Arun,

This is Nikolay from QuickBlox support.

Please check if the issue is still relevant for you.

If the issue persists, it may be due to the application not always connecting to the chat before sending messages. Please double-check the application logic related to the connection to the chat following our documentation:
[https://docs.quickblox.com/docs/flutter-chat-connection](https://docs.quickblox.com/docs/flutter-chat-connection)

Also, please provide us with full REST + XMPP logs as an attachment in .txt format. You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/section/14-gathering-logs-guides)

**Comment by KAUSHIKTECHIE** [comment] 2021-10-07 15:43
Facing the same issue.Could we have solution for this? It happens when I call send message API several times continuously.Can I get a quick solution to this.


I'm performing the necessary steps like login, connecting to chat server and joining dialog as per the doc and even before sending message I call all this . This issue not happening every time. Otherwise it is working perfect!

**Comment by ghost** [comment] 2021-10-08 09:40
Hello @KAUSHIKTECHIE ,

I will be happy to help you. However, I need more detailed information. 
To investigate the issue, please provide me with the following points:
1. Version of QuickBlox Flutter SDK. Please make sure that you use the latest version of the QuickBlox Flutter SDK.
Here is a link to download: [https://pub.dev/packages/quickblox_sdk](https://pub.dev/packages/quickblox_sdk)
2. Android version.
3. Devices in use (e.g. Redmi 8).
4. Flutter version.
5. Dart version.
6. What are the steps to reproduce on our side? Please explain the steps to me in more detail.
7. Please provide us with full REST + XMPP logs as an attachment in .txt format. There should be logs from the application start till the request and the "wrong" response (error).
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/section/14-gathering-logs-guides)

**Comment by KAUSHIKTECHIE** [comment] 2021-10-12 12:10
1.Version of QuickBlox Flutter SDK - ^0.6.2-beta
2.Android version - 5.1.1, 
3.Devices in use - vivo Y21L, 
4.Flutter version - 2.2.3
5.Dart version -  2.13.4
6.What are the steps to reproduce on our side? Please explain the steps to me in more detail --> I tried to Initialize SDK , then called Stream ,the made enable auto reconnect true in [main.dart.]
  I tried to Login -> Connect to chat server -> Subscribe to chat server event.
I join dialog -> Try to send message -> Crash occurs and uploaded the crash logs from Android Studio.
7. Please provide us with full REST + XMPP logs as an attachment in .txt format. --> Sent Attachment

[LogsForQb.txt.rtf.zip](https://github.com/QuickBlox/quickblox-flutter-sdk/files/7329732/LogsForQb.txt.rtf.zip)


We need some immediate solution for it. This crash occurs randomly but not for each message. Also doesn't throw in any of the catch block.

**Comment by ghost** [comment] 2021-10-13 10:07
@KAUSHIKTECHIE Thank you for your reply.

Please provide me with more detailed information about your application workflow related to joining dialogs. Please let me know if a message is automatically sent when a user is joined or a user sends a message manually.

As the issue happens not every time, it may be related to the joining to a dialog and answers from the Chat server.
Please double-check our documentation and make sure that the method is not executed asynchronously.
Here is a link:
https://docs.quickblox.com/docs/flutter-chat-dialogs#join-dialog

Additionally, as the issue is intermittent, please provide me with logs when messages are successfully sent and everything works correctly so I can compare them with the logs when the issue is present.

Also, please be aware of the difference between public and group dialogs. If a user wants to join a group dialog, the user should be added to occupants.
You may read more here:
https://docs.quickblox.com/docs/flutter-chat-dialogs#dialog-types

Please double-check the mentioned points and provide me with the requested information if the issue persists.

**Comment by KAUSHIKTECHIE** [comment] 2021-10-18 06:12
Application workflow -> I join the dialog then move to chat screen for send/receiving messages.I also tried Join dialog api if success then I goto send message api but it crashes still.
Crash happens intermittent also logs I have provided with many messages sent.
Also I am just testing public dialogs as of now.

Question :- 
1. Do we need to fire the join dialog API only once or for every message I fire join dialog and if success then goto send message API?
2. Do we need to check session for every API we call?
3. Chat server is connected every time we open the app in welcome screen.However I have call enableAutoReconnect.
4. I do sending/receiving UI logic for messages in subscribe Received Message event !!! Will this be any cause for the crash ???



[LogsForQb.txt.rtf.zip](https://github.com/QuickBlox/quickblox-flutter-sdk/files/7362200/LogsForQb.txt.rtf.zip)

**Comment by ghost** [comment] 2021-10-20 12:05
@KAUSHIKTECHIE 
A similar issue is being investigated by our developers. Once there is any news, we will let you know.

Please find the answers to your questions below:
>>-Do we need to fire the join dialog API only once or for every message I fire join dialog and if success then goto send message API?

You need to join a dialog only once. If you've successfully joined the dialog, you can send/receive messages in real-time. 

>>-Do we need to check session for every API we call?

You don’t need to check session every time.

>>-Chat server is connected every time we open the app in welcome screen.However I have call enableAutoReconnect.

This option should not cause issues.

>>-I do sending/receiving UI logic for messages in subscribe Received Message event !!! Will this be any cause for the crash ???

Please try implementing this functionality without custom UI logic and let us know if the issue persists. It may help us in investigating the issue.

Looking forward to hearing from you.

**Comment by ghost** [comment] 2022-02-17 15:22
@KAUSHIKTECHIE According to our developers, the issue with sending messages should be resolved in the new version of the SDK:
https://pub.dev/packages/quickblox_sdk/changelog#065-beta
Please update it and let us know if the issue is resolved.

**Closed as completed** 2023-01-11 10:14 UTC
