### ISSUE TITLE
Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel:

### ISSUE THREAD

**Issue by AnsarAzees** [QuickBlox/quickblox-flutter-sdk#31] opened 2021-07-28 15:08 UTC
Platform: Android
Quickblox version : 0.5.1-beta

When adding message subscription 

QB.chat.subscribeChatEvent(QBChatEvents.RECEIVED_NEW_MESSAGE,
      (data) {
         
      });

error message : Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send.

**Comment by ghost** [comment] 2021-08-12 09:33
Hello Ansar,

This is Nikolay from QuickBlox support.

Please try updating the QuickBlox Flutter SDK to the latest version (0.5.2-beta): [https://pub.dev/packages/quickblox_sdk/versions/0.5.2-beta](https://pub.dev/packages/quickblox_sdk/versions/0.5.2-beta)

If the issue persists, we will need the following points:
1. The detailed description of the issue.
2. When did this issue happen? Did the issue happen before or after implementing recent changes into your code?
3. Is this issue intermittent or permanent?
4. What are the steps to reproduce on our side?
5. Please provide us with full REST + XMPP logs as an attachment in .txt format. 
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/section/14-gathering-logs-guides)

Additionally, please make sure that you configured push notifications according to our guides: [Chat and video push notifications issue - QuickBlox Help Center](https://help.quickblox.com/section/2-chat-and-video-push-notifications-issue)

**Comment by GouthamJb** [comment] 2021-08-18 18:14
@AnsarAzees  
Hi,
Is this issue resolved? Any updates?

**Comment by GouthamJb** [comment] 2021-08-18 18:15
@QB-nikolay-zolotarov 
This issue is caused when  app is closed and opened again.

**Comment by GouthamJb** [comment] 2021-08-18 18:26
@QB-nikolay-zolotarov 
I am also facing the same issue in version 0.5.2-beta
Its working fine when app is installed for the 1st time but this issue is caused when app is closed and opened again.
Quickblox logs shows newly received messaged but the subscription event is not triggered.

D/SMACK   (21625): RECV (0): <message xmlns="jabber:client" id="611d4d530998b54c74fe01cf" type="groupchat" from="93271_611ccf130baecf007ee52de4@muc.chat.quickblox.com/129823322" to="129877920-93271@chat.quickblox.com/android_00000000-030a-4b3f-ffff-ffffef05ac4a"><body>hai</body><extraParams xmlns="jabber:client"><date_sent>1629310291</date_sent><save_to_history>1</save_to_history><dialog_id>611ccf130baecf007ee52de4</dialog_id><message_id>611d4d530998b54c74fe01cf</message_id></extraParams></message>
W/FlutterJNI(21625): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: FlutterQBChatChannel/RECEIVED_NEW_MESSAGE. Response ID: 0

permanent issue.

You can reproduce this error by closing the app and starting again.

**Comment by ghost** [comment] 2021-10-05 14:28
@AnsarAzees @GouthamJb 
Hello,

In order to investigate the issue further, please provide us with:
1. Full logs.
2. Step-by-step instructions on how to reproduce the issue.
3. Version of QuickBlox Flutter SDK.
4. Platform where the issue is reproduced (Android, iOS or both).
5. Version of the platform (e.g. Android 11, iOS 13).
6. Devices in use (e.g. Redmi 8).
7. Flutter version.
8. Dart version.

**Closed as completed** 2023-01-11 10:14 UTC
