### ISSUE TITLE
Regarding Push Notifications 

### ISSUE THREAD

**Issue by pranjaljain011** [QuickBlox/quickblox-flutter-sdk#25] opened 2021-06-01 10:30 UTC
I am not able to send chat notifications to users.  I am using -  0.3.9-alpha in this version.

**Comment by kirillTolmachev** [comment] 2021-06-11 11:33
@pranjaljain011 
Can you provide more information?
Logs and flow.
Tnanks.

**Comment by ghost** [comment] 2021-10-05 13:40
@pranjaljain011 Hello,

This is Nikolay from QuickBlox support.

Please make sure that you followed our documentation:
[https://docs.quickblox.com/docs/flutter-push-notifications
](https://docs.quickblox.com/docs/flutter-push-notifications
)
Please let me know if the issue is still relevant. If yes, please provide the required information:
1. Please provide full REST + XMPP logs as an attachment in .txt format.
You may use this guide: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/section/14-gathering-logs-guides)
2. More detailed information about the application workflow.
3. Version of QuickBlox Flutter SDK.
4. Platform where the issue is reproduced (Android, iOS, or both).
5. Version of the platform (e.g. Android 11, iOS 13).
6. Devices in use (e.g. Redmi 8)
7. Flutter version.
8. Dart version.

**Comment by ghost** [comment] 2021-12-07 12:56
@pranjaljain011 The issue is being closed as outdated.

If the issue is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 12:56 UTC
